language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install flake8

script:
  - make test

deploy:
  provider: pypi
  user: twopi-deploy
  password: "$PYPI_PASSWORD"
  on: 
    tags: true