language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install coveralls flake8
  - pip install .

script:
  - flake8 .
  - coverage run --source=twopi_flask_utils setup.py test

after_success:
  - coveralls

before_deploy:
  - git describe --tags --dirty --always --abbrev=0 > VERSION

deploy:
  provider: pypi
  user: twopi-deploy
  password: "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
